Render POI view with dummy data (closes #19)
mozilla-magnet/journey pull request #20
Opened 2017-01-21 00:14 UTC by wilsonpage

2017-01-21 00:15 UTC, wilsonpage commented
@gmarty r?

2017-01-23 13:58 UTC, gmarty requested changes
I left a few comments and questions but otherwise it looks good to me.

2017-01-23 13:58 UTC, gmarty commented on js/App.js
> +        var Component = this.routes[id].component;
nit: use `const`.

2017-01-23 13:58 UTC, gmarty commented on js/components/Header.js
> +  style: View.propTypes.style,
Can you explain me `View.propTypes.style`? I haven't seen this props validation syntax before and I can't find useful info about it.

2017-01-23 13:58 UTC, gmarty commented on js/scenes/Home.js
> +  const fetchedItems = itemIds.reduce((result, id) => {
It seems to me that what you're doing is really `filter`ing an array instead of `reduce`ing it.
Or am I missing something?

2017-01-23 13:58 UTC, gmarty commented on js/scenes/Item.js
> +        resizeMode={Image.resizeMode.cover}
According to the doc, the `resizeMode` accepts a string, so it should read `resizeMode="cover"`.
Maybe it has changed in the last few versions.

2017-01-23 13:58 UTC, gmarty commented on js/scenes/Item.js
> +        style={[styles.loading]} size="large" />
nit: no space before closing tag: `/>`.

2017-01-23 13:58 UTC, gmarty commented on js/scenes/Item.js
> +const mapStateToProps = ({itemsCache }, { itemId }) => {
nit: space after opening curly bracket.

2017-01-23 13:58 UTC, gmarty commented on js/store/reducers.js
> +  }, {});
You probably want to `filter` here instead of `reduce`ing.

2017-01-23 13:58 UTC, gmarty commented on js/scenes/Home.js
> +      data: { itemId: id },
If you call the parameter `itemId` in `onItemPress()` you can simply do:
```js
data: { itemId },
```

2017-01-23 16:25 UTC, wilsonpage commented on js/App.js
> +        var Component = this.routes[id].component;
Linter wouldn't let me use `const` here. Something to do with lexical scope.

2017-01-23 16:27 UTC, wilsonpage commented on js/components/Header.js
> +  style: View.propTypes.style,
It basically means you can pass style as either an object (`{ flex: 1 }`) or a `Stylesheet` property (`styles.foo`). It extends how RN views handle style.

2017-01-23 16:31 UTC, wilsonpage commented on js/scenes/Home.js
> +  const fetchedItems = itemIds.reduce((result, id) => {
A filter would just just return a list of ids, but actually want to inflate the list into fetched item objects. If items aren't in the `itemsCache` yet, I don't want to render them. I guess I could do `.filter()` then `.map()`?

2017-01-23 16:34 UTC, gmarty commented on js/App.js
> +        var Component = this.routes[id].component;
Oh I see, in this case, you should be able to use `let`.

2017-01-23 17:55 UTC, wilsonpage commented on js/App.js
> +        var Component = this.routes[id].component;
It wouldn't let me use `let` either. `var` is the only declaration that passed linter.

2017-01-23 17:58 UTC, wilsonpage commented on js/scenes/Item.js
> +        resizeMode={Image.resizeMode.cover}
That syntax works too, but in [the examples ](https://facebook.github.io/react-native/docs/image.html) they show using the constant.

2017-01-23 18:00 UTC, wilsonpage commented on js/store/reducers.js
> +  }, {});
I don't want to filter down the list, I want to transform it into an Array of Strings and an object. I think I could use a `.map()`, return just the ids and create the `toCache` object inside that loop.

2017-01-23 18:01 UTC, gmarty commented on js/App.js
> +        var Component = this.routes[id].component;
OK for this time, I'm planning on adding more options to ESLint, including forbidding the use of `var`. I can take a look at this file when I work on it.

2017-01-23 18:02 UTC, gmarty commented on js/scenes/Home.js
> +  const fetchedItems = itemIds.reduce((result, id) => {
filter and map sounds easier to understand to me.
If you think that in general reduce is OK for most people, just leave it as is.

2017-01-23 18:03 UTC, gmarty commented on js/scenes/Item.js
> +        resizeMode={Image.resizeMode.cover}
The string is easier to read and remember I think.

2017-01-23 18:05 UTC, samgiles commented on js/store/reducers.js
> +  }, {});
I would try not to worry too much about caching in the store - the journey-data library will know more about what caching rules to use, when to cache, when not to, what's stale etc.

2017-01-23 18:10 UTC, arcturus commented on js/store/reducers.js
> +  }, {});
+1 to @samgiles \o/

2017-01-23 18:11 UTC, wilsonpage commented on js/store/reducers.js
> +  }, {});
@samgiles I don't know enough about how this journey-data part will work yet. Are you saying Redux shouldn't hold any detailed item state? I was expecting the journey-data API would be treated similar to a REST API; Redux would fetch bunch of items from it, store them internally, pass them to React to render, and periodically update its 'cache'.

2017-01-23 21:27 UTC, merged