Add a visual component for profile link
mozilla-magnet/journey pull request #35
Opened 2017-01-25 14:51 UTC by gmarty

2017-01-25 22:37 UTC, wilsonpage requested changes
Looking good! Comments:

- Wire up with real data from the API.
- Replace `<Profile>` with a `<LIstItem>` component. The component is unlikely to be reused in the ItemScene.

2017-01-25 22:37 UTC, wilsonpage commented on js/scenes/Home.js
> +              source={require('../images/dummy/dank.jpg')}
Can we use real data here? If it's not in the dummy data it can be added.

2017-01-25 22:37 UTC, wilsonpage commented on js/scenes/Home.js
> +            <Profile
Is it worth having a separate component for this? IMO it should be a detail of a `ListItem` component, unless we see somewhere else it will be used?

2017-01-25 22:37 UTC, wilsonpage commented on js/scenes/Item.js
> +          <Profile
Ah I see you're using it here too now which makes sense for it being its own component. But are the designs the same?

2017-01-26 11:07 UTC, arcturus commented
Could you rebase?

2017-01-26 11:30 UTC, arcturus commented
+1 to make this component configurable so we can drop it on the list view, item view, and also in the poi view, with a bigger size.

2017-01-27 13:03 UTC, gmarty commented
I made it a ListItem component after the discussions of yesterday.

2017-01-30 18:15 UTC, wilsonpage approved these changes
Nice, looks good!

2017-01-31 00:15 UTC, wilsonpage commented
Landed as part of 47e76d1f5f514472e675c8f41a28cef3dfdda158

2017-01-31 00:15 UTC, closed without merging