Full screen experience - Content scroll underneath transparent status bar
mozilla-magnet/journey pull request #49
Opened 2017-01-31 14:40 UTC by gmarty

Full screen experience for added beauty.

See #43.

2017-01-31 15:21 UTC, arcturus commented on js/App.js
> +      default: {
Are the curly brackets needed?

2017-01-31 15:22 UTC, arcturus commented on js/components/Header.js
> +const STATUS_BAR_HEIGHT = Platform.OS === 'ios' ? 20 : StatusBar.currentHeight;
Can we make the values 20 and 54 constants with self explained name?

2017-01-31 15:23 UTC, arcturus commented
lgtm, left some nit comments.

2017-01-31 17:49 UTC, wilsonpage commented
I'm not sure this is ok:

<img width="376" alt="screen shot 2017-01-31 at 09 48 01" src="https://cloud.githubusercontent.com/assets/1020551/22477314/6b1061a4-e79a-11e6-82a3-ac3777e4d19f.png">

Perhaps we need to pad the list-item content in a bit more?

2017-01-31 17:52 UTC, wilsonpage commented
Also on Android:

<img width="308" alt="screen shot 2017-01-31 at 09 50 21" src="https://cloud.githubusercontent.com/assets/1020551/22477400/c3fcd50e-e79a-11e6-8f12-238fb60eb22c.png">

Overlapping components is not OK IMO. We may be able to pad in the list-item contents a little more and add some kind of semi-opaque black background to the system status-bar. But I fear that this might look strange still.

2017-01-31 17:55 UTC, wilsonpage requested changes
This isn't looking right at the moment. An Android status bar with lots of notification icons is going to look messy overlaid on top of the publisher profile and star components.

Wondering if there is a way to scroll the content under the status bar but have it offset by the height of the status-bar when scrollTop is `0`. The hidden header UI will make this complex to implement.

2017-01-31 17:59 UTC, gmarty commented
I reckon it looks weird, but I thought that'd help for the discoverability of the hidden header.
I'll keep working on this PR and see what I can do to make it look better.

2017-01-31 22:15 UTC, wilsonpage commented
I was drinking a coffee and had an idea! All we have to do is increase the `paddingTop` for the first list item. That way it will look neat when at scroll-top, works with the hidden heading interaction and is hidden out of view when list is at any other scroll position.

2017-02-01 11:06 UTC, gmarty commented on js/App.js
> +      default: {
Yes, its to create a new scope to allow the use of `const`.

2017-02-01 11:08 UTC, gmarty commented on js/components/Header.js
> +const STATUS_BAR_HEIGHT = Platform.OS === 'ios' ? 20 : StatusBar.currentHeight;
20 is the height of the status bar on iOS. In Android, we can just use `StatusBar.currentHeight`.
54 is the height we want the header to have. This should be pretty self explanatory already.

2017-02-01 12:58 UTC, gmarty commented
So in this update, I added a grey margin on top of the first item, but then scrolling down will reveal the header. I had to reduce the header to subtract the height of the status bar and fix the vertical positioning. It's not as hackish as it sounds and the result is nice.
The default view still show a dark header on top of the first item so it's not as nice as before but at least here all items have exactly the same template.

Let's land this now and we can always revisit it later.

2017-02-01 20:35 UTC, wilsonpage requested changes
We're almost there, but can't land this if the `firstRow` element is blocking touches on `<Header>`

2017-02-01 20:35 UTC, wilsonpage commented on js/App.js
> +          backgroundColor="transparent"
Can we keep a bit of background color so that if status-bar icons are over a white background (in our app) they are still visible?

2017-02-01 20:35 UTC, wilsonpage commented on js/scenes/Home.js
> +    };
This is really funky syntax, can you find an alternative :-/

2017-02-01 20:35 UTC, wilsonpage commented on js/scenes/Home.js
> +      <View style={styles.firstRow}/>
This element overhangs the header content and blocks the header buttons. 'Settings' button is difficult to press.

2017-02-01 20:35 UTC, wilsonpage commented on js/scenes/Home.js
> +      outputRange: [0, Header.HEIGHT - Header.STATUS_BAR_HEIGHT],
Can you do this calculation once?

```js
const MAX_Y = Header.HEIGHT - Header.STATUS_BAR_HEIGHT;
```

2026-05-01 18:25 UTC, closed without merging