Compass component
mozilla-magnet/journey pull request #6
Opened 2017-01-18 15:31 UTC by arcturus

Adding the compass component.

Also added a debug scene that is loaded just in debug builds (accessible from the Settings scene). That view has a version of the compass pointing towards the shard. Also there you can see how the component is used (it will require to know what's the latitude and longitude of your location and the point you want to point to).

Considerations:
- In ios sensors works beautifully and there is no problems
- In android sensors may take a while until having a good reading and you will see how the arrow moves slowly until we get real data. We can 'calibrate' the compass by asking the user to do an '8' with the phone, it's unfortunately something that happens in android apps. Right now we don't detect the accuracy of the reading, but we could, in order to show a message like that this: http://uploads.tapatalk-cdn.com/20150824/8367bca44f8cca19edfa97d5092fce99.jpg

Created an app to try out several of this compasses working at the same time and works beautifully:
![img_0001](https://cloud.githubusercontent.com/assets/60801/22070207/197bf1ca-dd93-11e6-8b9c-6d6ef62eaf5c.PNG)

Here is the repo if you want to play with it:
https://github.com/arcturus/ReactnativeCompass

@gmarty @wilsonpage r?

2017-01-18 15:47 UTC, wilsonpage commented on package.json
> +    "react-native-heading": "git://github.com/arcturus/react-native-heading.git",
What changes does your fork contain?

2017-01-18 15:49 UTC, arcturus commented on package.json
> +    "react-native-heading": "git://github.com/arcturus/react-native-heading.git",
I need it to be compatible with react 0.40 for iOS, did a PR to the original repo but after 1 week has not been merged.

Also the guy has a pending PR that I've checked to be good, so I added to the fork.
The rest is the same.

2017-01-18 15:52 UTC, wilsonpage commented on js/components/Compass/index.js
> +module.exports = Compass;
You're exporting the class twice. See above (line9).

2017-01-18 15:53 UTC, wilsonpage commented on js/scenes/Debug.js
> +}
NIT: Indentation

2017-01-18 15:53 UTC, arcturus commented on js/components/Compass/index.js
> +module.exports = Compass;
Do'h! Good catch.

2017-01-18 15:55 UTC, wilsonpage commented on js/scenes/Settings.js
> +  onNavigate(id) {
NIT: Naming: This isn't a response/event to navigation but an instruction to navigate.

`onNavigate` -> `navigate`

2017-01-18 15:58 UTC, wilsonpage commented on js/scenes/Settings.js
> +    }
NIT: Unnecessary `else`.

```js
renderDebug() {
  if (!__DEV__) return;
  return <TouchableOpacity onPress={this.onNavigate.bind(this, 'debug')}>
     <Text style={styles.text}>Go to Debug</Text>
  </TouchableOpacity>;
}
```

2017-01-18 16:00 UTC, wilsonpage commented on js/scenes/Debug.js
> +  componentWillUnmount() {
NIT: Can this be after `componentDidMount` so we see setup then teardown when reading.

2017-01-18 16:02 UTC, wilsonpage commented on js/scenes/Debug.js
> +    navigator.geolocation.getCurrentPosition( (position) => {
I think eventually the user's current position should be handled globally by Redux. This component could be dumber and just be passed a `deviceLocation` prop.

2017-01-18 16:04 UTC, wilsonpage commented on js/components/Compass/index.js
> +  degreesFilter: React.PropTypes.number,
What do `azimut` and `degreesFilter` mean?

2017-01-18 16:04 UTC, wilsonpage commented on js/components/Compass/index.js
> +            headingIsSupported: didStart,
NIT: indentation

2017-01-18 16:06 UTC, wilsonpage commented on js/components/Compass/index.js
> +    ReactNativeHeading.start(this.state.angleFilter)
If we have lots of these components, does it matter if `start` is called several times? Again I think eventually state like this should be passed in and managed by Redux.

2017-01-18 16:07 UTC, wilsonpage commented on js/components/Compass/index.js
> +    })}]}]}
NIT: Kinda hard to parse this line.

2017-01-18 16:10 UTC, arcturus commented on js/scenes/Settings.js
> +    }
That's horrendous! Difficult to see there is two paths in that function :P

2017-01-18 16:11 UTC, arcturus commented on js/scenes/Debug.js
> +    navigator.geolocation.getCurrentPosition( (position) => {
Yes, I think we will have an unique source of truth for the location, but until we have that, (we marked as one of the components), I was using that cheap way of having location for testing the component.

2017-01-18 16:12 UTC, wilsonpage commented on js/scenes/Settings.js
> +    }
Well it's essentially a `guard`. If we're not in DEV mode it's a noop. Francisco style:

```js
renderDebug() {
  if (!__DEV__) {
    return;
  }

  return <TouchableOpacity onPress={this.onNavigate.bind(this, 'debug')}>
     <Text style={styles.text}>Go to Debug</Text>
  </TouchableOpacity>;
}
```

2017-01-18 16:12 UTC, arcturus commented on js/components/Compass/index.js
> +    ReactNativeHeading.start(this.state.angleFilter)
It doesn't matter, same than gps is a sensor that is being already used, and we will listen to the updated values.

2017-01-18 16:14 UTC, arcturus commented on js/components/Compass/index.js
> +  degreesFilter: React.PropTypes.number,
azimut ... damn! I used the Spanish and French version, in English is azimuth, it's pretty much the naming you use to refer to what's your reference, north, when computing locations, angles and so on. But it's true I need to rename it to proper English.

2017-01-18 16:17 UTC, wilsonpage commented on js/components/Compass/index.js
> +  degreesFilter: React.PropTypes.number,
Oh, well I've never heard of either :p

2017-01-18 16:18 UTC, gmarty requested changes
Looks good to me.
The trigonometric computations works for us but might not at the scale of earth.

A few comments left but ship it!!

2017-01-18 16:18 UTC, gmarty commented on ios/MagnetJourney/Info.plist
> +	<false/>
Most of the stuff has just been reorganised?
It's hard to tell what changed.

2017-01-18 16:18 UTC, gmarty commented on js/components/Compass/index.js
> +
nit: no line break. See other files for coding style.
You can also run `yarn run fix` to fix potential basic issues with styling.

2017-01-18 16:18 UTC, gmarty commented on js/components/Compass/index.js
> +    .then(didStart => {
nit: this block should be indented.

2017-01-18 16:18 UTC, gmarty commented on js/components/Compass/index.js
> +    .then(didStart => {
what about:
```js
.then(headingIsSupported => {
  this.setState({ headingIsSupported })
});
```

2017-01-18 16:18 UTC, gmarty commented on js/components/Compass/index.js
> +    return parseInt(this.toDegrees(radiansBearing));
is `parseInt` neeeded here?

2017-01-18 16:18 UTC, gmarty commented on js/scenes/Debug.js
> +});
Add a line break at the end of files.

2017-01-18 16:18 UTC, gmarty commented on js/scenes/Settings.js
> +  onNavigate(id) {
I'd say `onNavigationChange` though to make the relation with a user interaction more obvious.

2017-01-18 16:18 UTC, gmarty commented on js/components/Compass/index.js
> +    if (offset != 0) {
Surely it won't hurt if you subtract 0.

2017-01-18 16:32 UTC, arcturus commented on js/scenes/Debug.js
> +  componentWillUnmount() {
Yup, good catch.

2017-01-18 16:36 UTC, wilsonpage commented
I need to test on device when I get into the office but code looks good to me. Although I don't know anything about trigonometry, angles and all that jazz. Seems @gmarty knows more about that :)

2017-01-18 16:40 UTC, arcturus commented on js/components/Compass/index.js
> +  degreesFilter: React.PropTypes.number,
degreesFilter is the number of degrees your heading has to change in order to notify of a change.

The hardware is going to be constantly giving values, different values, even if we are quiet, so we need to have a threshold to not to make the arrow shake too much.

2017-01-18 16:41 UTC, arcturus commented on js/components/Compass/index.js
> +    })}]}]}
Will try my best, but believe me the syntax for interpolation in animations is complicated.

2017-01-18 16:46 UTC, arcturus commented on js/scenes/Settings.js
> +    }
Ok, I can do that :) ... we should use more Francisco's style.

2017-01-18 16:47 UTC, arcturus commented on ios/MagnetJourney/Info.plist
> +	<false/>
Those are automatic changes done by xcode :S

2017-01-18 16:48 UTC, arcturus commented on js/components/Compass/index.js
> +    if (offset != 0) {
Yes it wont :), also the checking of the latitude and longitude is happening in calculateOffset so is safe to skip that check.

2017-01-18 16:49 UTC, arcturus commented on js/components/Compass/index.js
> +    return parseInt(this.toDegrees(radiansBearing));
Yes, we need to return integers, so the animation interpolation can go from 0 deg to 360 deg and the animation comes for free in react native.

2017-01-18 22:10 UTC, wilsonpage commented on js/components/Compass/index.js
> +/* global require */
Why is this needed? If we support `require()` syntax can't we define that globally in the app's `.eslintrc`?

2017-01-19 01:22 UTC, wilsonpage commented
Having trouble building on Android:

<img width="1392" alt="screen shot 2017-01-18 at 17 21 53" src="https://cloud.githubusercontent.com/assets/1020551/22089840/abb6c600-dda2-11e6-8773-b596a7d71bf9.png">

2017-01-19 01:27 UTC, wilsonpage commented
I cast to `int` and seems to be working :-/

```java
newAzimuth = (int) ...
```

Rotation looks nice and smooth. Really cool to see this working!

2017-01-19 01:28 UTC, wilsonpage commented
@arcturus so not sure what do do about the compiler error in `react-native-heading`. Strange that you don't have it.

2017-01-19 01:29 UTC, wilsonpage commented
I tried to test on IOS but I think I'm missing some kind of certificate to build on a real device. Help needed :)

2017-01-19 01:29 UTC, wilsonpage commented
Debug menu is missing a back button.

2017-01-19 13:21 UTC, arcturus commented
Good catch with the android version, had it modified locally but didn't push it.

2017-01-19 13:45 UTC, arcturus commented
Added back button to the debug build.

2017-01-19 14:06 UTC, arcturus commented
I did rebase, but seems that now the react-native-heading is not compiling in the new workspace :(

2017-01-20 12:05 UTC, arcturus commented
Finally found the problem, it took me a whole day.

With the new cocoapods, in order to compiile the library libreactheading we need to change the search for the headers library to where the headers are now (after using pods):
$(SRCROOT)/../../ios/Pods/Headers/Private/React/**

😭 😭 😭 😭 😭 😭 😭

2017-01-20 14:33 UTC, arcturus commented
Had to change to npm in CI since yarn is hanging while downloading packages:

https://github.com/yarnpkg/yarn/issues/764

2017-01-20 14:34 UTC, merged